language: java

sudo: false

services:
  - docker

jdk:
  - oraclejdk9
  - openjdk10
  - oraclejdk11
  - openjdk12

install: true

# docker-maven-plugin needs access to this module
before_script: if [ "$TRAVIS_JDK_VERSION" = "oraclejdk9" ] || [ "$TRAVIS_JDK_VERSION" = "openjdk10" ]; then export MAVEN_OPTS="--add-modules java.activation"; fi

script:
  - mvn verify
  - docker run -it --rm maven-jlink-docker-example

cache:
  directories:
    - '$HOME/.m2/repository'
