language: java

sudo: false

services:
  - docker

jdk:
  - oraclejdk9
  - openjdk10
  - oraclejdk11
  - openjdk12

install: true

script:
  - mvn verify
  - docker run -it --rm maven-jlink-docker-example

cache:
  directories:
    - '$HOME/.m2/repository'
